services:
  - type: web
    name: api-internet-banking
    runtime: docker
    region: frankfurt
    plan: free
    rootDir: server
    dockerfilePath: server/backend/Dockerfile
    dockerBuildContext: server/backend
    healthCheckPath: /health
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: docker
      - key: DB_HOST
        fromService:
          type: pserv
          name: intbank-db
          property: host
      - key: DB_PORT
        fromService:
          type: pserv
          name: intbank-db
          property: port
      - key: DB_NAME
        sync: false
      - key: DB_USER
        sync: false
      - key: DB_PASSWORD
        sync: false
      - key: REDIS_HOST
        fromService:
          type: pserv
          name: intbank-redis
          property: host
      - key: REDIS_PORT
        fromService:
          type: pserv
          name: intbank-redis
          property: port
      - key: KAFKA_BOOTSTRAP_SERVERS
        sync: false
    autoDeploy: true