'use strict';

// Banking constants
const BANK_CODE = 'INTB';
const IBAN_ACCOUNT_LENGTH = 16;
const CARD_BIN = '499999';
const CARD_LENGTH = 16;
const DEFAULT_CARD_LIFETIME_YEARS = 3;
const MAX_RETRIES = 7;

// Crypto constants
const AES_GCM_IV_BYTES = 12;
const AES_GCM_TAG_BYTES = 16;

// Rate limit constants
const LOGIN_WINDOW_MS = 60 * 60 * 1000; // 1 hour
const LOGIN_MAX_ATTEMPTS = 10;
const TWOFA_REQUEST_MAX = 3;
const TWOFA_VERIFY_MAX = 6;
const TWOFA_VERIFY_WINDOW_MS = 15 * 60 * 1000; // 15 minutes
const USERS_WINDOW_MS = 10 * 60 * 1000; // 10 minutes
const USERS_MAX_REQUESTS = 200;
const GLOBAL_WINDOW_MS = 60 * 1000; // 1 minute
const GLOBAL_MAX_REQUESTS = 150;

module.exports = {
  BANK_CODE,
  IBAN_ACCOUNT_LENGTH,
  CARD_BIN,
  CARD_LENGTH,
  DEFAULT_CARD_LIFETIME_YEARS,
  MAX_RETRIES,
  AES_GCM_IV_BYTES,
  AES_GCM_TAG_BYTES,
  LOGIN_WINDOW_MS,
  LOGIN_MAX_ATTEMPTS,
  TWOFA_REQUEST_MAX,
  TWOFA_VERIFY_MAX,
  TWOFA_VERIFY_WINDOW_MS,
  USERS_WINDOW_MS,
  USERS_MAX_REQUESTS,
  GLOBAL_WINDOW_MS,
  GLOBAL_MAX_REQUESTS,
};
